### ISSUE TITLE
for-4.14: unable to reference part_inc_in_flight() and part_dec_in_flight().

### ISSUE THREAD

**Issue by cupnes** [walb-linux/walb-driver#2]
# 問題点
Linux 4.14-rc4現在、後述[*1]のコミットにより part_inc_in_flight()、part_dec_in_flight()、part_in_flight() がカーネルモジュールから参照できなくなります。

# walb-driverへの影響
walb-driverでは以下の箇所で part_inc_in_flight() と part_dec_in_flight() を使用しており、これらの関数を使用しない方法へ修正する必要があります。

- part_inc_in_flight() 使用箇所(module/io.c 2867行目)
  - http://github.com/walb-linux/walb-driver/blob/65f6f5c/module/io.c#L2867
- part_dec_in_flight() 使用箇所(module/io.c 2887行目)
  - http://github.com/walb-linux/walb-driver/blob/65f6f5c/module/io.c#L2887

# 問題のコミットについて
[*1] blk-mq: provide internal in-flight variant
http://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f299b7c

[*1]には、 include/linux/genhd.h へ実装していた part_inc_in_flight()、part_dec_in_flight()、part_in_flight() を、 block/genhd.c へ移す変更も含まれています。

ただし、コミットタイトルの通り、これらの関数はinternal用途であり、カーネルモジュールへ使用させる意図は無い様です[*2]。おそらくそのために、[*1]のコミットでは問題の3つの関数の実装を block/genhd.c へ移す際、 EXPORT_SYMBOL() していないものと思われます。

[*2] 4.14-rc4のdriversディレクトリをgrepする限り、問題の3つの関数を使用するカーネルモジュールはありませんでした。

**Comment by starpos** [comment]
コメントありがとうございます。
kernel 3.2 のときに DRBD のコードを参考に追加したコードをそのまま使ってきました。
それに倣うとすると、
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=244808543e6e9b46ea1135589877f4d4bd2925c5
このあたりを参考にすればいいのかなと思います。

**Comment by cupnes** [comment]
ありがとうございます。なるほどです。

以下のコミットで generic_start_io_acct() と generic_end_io_acct() というインタフェースが追加されていたのですね。
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=394ffa5

まだWIPですが、パッチを作ってみました。modprobe成功まで確認しています。
https://github.com/cupnes/walb-driver/commit/791d01390ccfbde37d17f91d33657d9a224e7c34
