### ISSUE TITLE
Can this project apply to devices on which a filesystem has been created?

### ISSUE THREAD

**Issue by mlcdev2024** [walb-linux/walb-driver#6]
Firstly, I'm highly appreciated for this great project and your excellent job.
I've gone through a primary test on this driver with walb-tools following a tutorial. I learned that a WalB block device(wdev) is a wrapper around a data block device and a log block device, and a filesystem is created on the wdev. But as mostly situation, a data block device(i.e. WalB data device) has already been in use currently, which means a filesystem has been created on top of that. And I want to do full/incremental backup on this data block device, then how to create a wdev wrapper around it? Is this driver applicable to this situation and how to cater to? I haven't delved deeply into the source code or maybe I've missed something. 
Any insights or suggestions would be greatly appreciated! @starpos

**Comment by starpos** [comment]
Thanks for your interest in WalB. What you want to do will be accomplished as follows:
(1) Prepare a data device (ddev) with any contents.
(2) Prepare a log device (ldev) that will be overwritten.
(3) Create a wdev using the ddev and ldev. The contents of the ddev will not be lost and can be accessed through the wdev. Writes are stored internally in the both devices to maintain overall consistency.
(4) Updates to the contents on the ddev will be delayed while the wdev is running. We assume the full backup reads the wdev, not the ddev. The copied full image is not consistent, so the wlogs during the full backup must also be extracted to synthesize a consistent snapshot image later.

Safe wdev shutdown applies all wlogs to the ddev. This assumes, of course, that there are no writes to the wdev at all.  This property enables assembling and disassembling a wdev can be executed without loosing the contents that the ddev having.

**Comment by mlcdev2024** [comment]
Thanks for your rapid reply. @starpos 
I completed my test once again following your instructions, and yeah, it worked for me, although a little glitch still arose.
I had a ddev, on which a filesystem(e.g. a EXT4 filesystem) had been mounted to a directory. But when I invoked create-wdev through wdevc to create a wdev based on the ddev, it ran into an error. I guessed that maybe the situation that the filesystem had been mounted on the ddev led to this problem. So I unmounted the filesystem, and do it again, then it worked smoothly this time. So I conclude that a filesystem that has been mounted on ddev should be unmounted first, and be mounted on wdev instead. If so, the entire procedure would not be transparent to the users of the filesystem. Am I right? Could you give me some pointers?

**Comment by starpos** [comment]
Your experienced behavior is expected one. "Online" assembling/disassembling of wdev is not possible (with current implementation). Assembling (or disassembling) wdev requires that no one is using the corresponding devices. If you want transparent behavior for filesystems, you need another wrapper device that internally switchs the filesystem device between wdev and ddev. Of cource such a functionality is indepenent from WalB functionality and is not provided by WalB driver.

**Comment by mlcdev2024** [comment]
Thanks for your suggestions, which would be put into our considerations. But a sudden brainstorm springs into my mind, which is intercepting bio (block I/O) streaming of a block device(actual data device like ddev) in the kernel and writing it to a write-ahead log (WAL) before actually writing it to disk. With this approach, maybe the ddev won't experience a downtime, but can also continuously export I/O log to the WAL. Of course, it is just an idea and remains to be verified.

**Comment by starpos** [comment]
I am not sure what your idea is trying to solve. I think it would be impossible to switch the block device that is being mounted while the filesystem is still online. That's why I said that you would need a wrapper device that internally switches the target device, even though it is not switched from the filesystem's point of view. The wrapper device driver will (1) stop writing to the underlying device, (2) prepare another underlying device with the same contents, (3) switch the underlying device to the new one, and (4) restart writing.

**Comment by mlcdev2024** [comment]
Well, basically our core requirements include two sides: 1) we want to export WAL of a device for backup and replication, 2) We can't afford downtime of the device that maybe is being used by an application(DBMS, for example).
